# Generated by Django 4.1 on 2022-08-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='last_name',
        ),
    ]
