# Generated by Django 4.1 on 2022-08-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_remove_subscriber_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
