# Generated by Django 3.2.10 on 2022-08-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('current_weight', models.IntegerField(default=0)),
                ('goal_weight', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('bmi', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
