# Generated by Django 4.1 on 2022-08-09 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_queries_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 12, 26, 59, 201572, tzinfo=datetime.timezone.utc)),
        ),
    ]
