# Generated by Django 4.1 on 2022-08-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='mobile_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='mobile_number'),
        ),
    ]
